// Code generated by "enumer -linecomment -type=PlotProperty ."; DO NOT EDIT.

package giu

import (
	"fmt"
	"strings"
)

const _PlotPropertyName = "PlotPropertyLineColorPlotPropertyLineColorsPlotPropertyLineWeightPlotPropertyFillColorPlotPropertyFillColorsPlotPropertyFillAlphaPlotPropertyMarkerPlotPropertyMarkerSizePlotPropertyMarkerSizesPlotPropertyMarkerLineColorPlotPropertyMarkerLineColorsPlotPropertyMarkerFillColorPlotPropertyMarkerFillColorsPlotPropertySizePlotPropertyOffsetPlotPropertyStridePlotPropertyFlags"

var _PlotPropertyIndex = [...]uint16{0, 21, 43, 65, 86, 108, 129, 147, 169, 192, 219, 247, 274, 302, 318, 336, 354, 371}

const _PlotPropertyLowerName = "plotpropertylinecolorplotpropertylinecolorsplotpropertylineweightplotpropertyfillcolorplotpropertyfillcolorsplotpropertyfillalphaplotpropertymarkerplotpropertymarkersizeplotpropertymarkersizesplotpropertymarkerlinecolorplotpropertymarkerlinecolorsplotpropertymarkerfillcolorplotpropertymarkerfillcolorsplotpropertysizeplotpropertyoffsetplotpropertystrideplotpropertyflags"

func (i PlotProperty) String() string {
	if i >= PlotProperty(len(_PlotPropertyIndex)-1) {
		return fmt.Sprintf("PlotProperty(%d)", i)
	}
	return _PlotPropertyName[_PlotPropertyIndex[i]:_PlotPropertyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PlotPropertyNoOp() {
	var x [1]struct{}
	_ = x[PlotPropertyLineColor-(0)]
	_ = x[PlotPropertyLineColors-(1)]
	_ = x[PlotPropertyLineWeight-(2)]
	_ = x[PlotPropertyFillColor-(3)]
	_ = x[PlotPropertyFillColors-(4)]
	_ = x[PlotPropertyFillAlpha-(5)]
	_ = x[PlotPropertyMarker-(6)]
	_ = x[PlotPropertyMarkerSize-(7)]
	_ = x[PlotPropertyMarkerSizes-(8)]
	_ = x[PlotPropertyMarkerLineColor-(9)]
	_ = x[PlotPropertyMarkerLineColors-(10)]
	_ = x[PlotPropertyMarkerFillColor-(11)]
	_ = x[PlotPropertyMarkerFillColors-(12)]
	_ = x[PlotPropertySize-(13)]
	_ = x[PlotPropertyOffset-(14)]
	_ = x[PlotPropertyStride-(15)]
	_ = x[PlotPropertyFlags-(16)]
}

var _PlotPropertyValues = []PlotProperty{PlotPropertyLineColor, PlotPropertyLineColors, PlotPropertyLineWeight, PlotPropertyFillColor, PlotPropertyFillColors, PlotPropertyFillAlpha, PlotPropertyMarker, PlotPropertyMarkerSize, PlotPropertyMarkerSizes, PlotPropertyMarkerLineColor, PlotPropertyMarkerLineColors, PlotPropertyMarkerFillColor, PlotPropertyMarkerFillColors, PlotPropertySize, PlotPropertyOffset, PlotPropertyStride, PlotPropertyFlags}

var _PlotPropertyNameToValueMap = map[string]PlotProperty{
	_PlotPropertyName[0:21]:         PlotPropertyLineColor,
	_PlotPropertyLowerName[0:21]:    PlotPropertyLineColor,
	_PlotPropertyName[21:43]:        PlotPropertyLineColors,
	_PlotPropertyLowerName[21:43]:   PlotPropertyLineColors,
	_PlotPropertyName[43:65]:        PlotPropertyLineWeight,
	_PlotPropertyLowerName[43:65]:   PlotPropertyLineWeight,
	_PlotPropertyName[65:86]:        PlotPropertyFillColor,
	_PlotPropertyLowerName[65:86]:   PlotPropertyFillColor,
	_PlotPropertyName[86:108]:       PlotPropertyFillColors,
	_PlotPropertyLowerName[86:108]:  PlotPropertyFillColors,
	_PlotPropertyName[108:129]:      PlotPropertyFillAlpha,
	_PlotPropertyLowerName[108:129]: PlotPropertyFillAlpha,
	_PlotPropertyName[129:147]:      PlotPropertyMarker,
	_PlotPropertyLowerName[129:147]: PlotPropertyMarker,
	_PlotPropertyName[147:169]:      PlotPropertyMarkerSize,
	_PlotPropertyLowerName[147:169]: PlotPropertyMarkerSize,
	_PlotPropertyName[169:192]:      PlotPropertyMarkerSizes,
	_PlotPropertyLowerName[169:192]: PlotPropertyMarkerSizes,
	_PlotPropertyName[192:219]:      PlotPropertyMarkerLineColor,
	_PlotPropertyLowerName[192:219]: PlotPropertyMarkerLineColor,
	_PlotPropertyName[219:247]:      PlotPropertyMarkerLineColors,
	_PlotPropertyLowerName[219:247]: PlotPropertyMarkerLineColors,
	_PlotPropertyName[247:274]:      PlotPropertyMarkerFillColor,
	_PlotPropertyLowerName[247:274]: PlotPropertyMarkerFillColor,
	_PlotPropertyName[274:302]:      PlotPropertyMarkerFillColors,
	_PlotPropertyLowerName[274:302]: PlotPropertyMarkerFillColors,
	_PlotPropertyName[302:318]:      PlotPropertySize,
	_PlotPropertyLowerName[302:318]: PlotPropertySize,
	_PlotPropertyName[318:336]:      PlotPropertyOffset,
	_PlotPropertyLowerName[318:336]: PlotPropertyOffset,
	_PlotPropertyName[336:354]:      PlotPropertyStride,
	_PlotPropertyLowerName[336:354]: PlotPropertyStride,
	_PlotPropertyName[354:371]:      PlotPropertyFlags,
	_PlotPropertyLowerName[354:371]: PlotPropertyFlags,
}

var _PlotPropertyNames = []string{
	_PlotPropertyName[0:21],
	_PlotPropertyName[21:43],
	_PlotPropertyName[43:65],
	_PlotPropertyName[65:86],
	_PlotPropertyName[86:108],
	_PlotPropertyName[108:129],
	_PlotPropertyName[129:147],
	_PlotPropertyName[147:169],
	_PlotPropertyName[169:192],
	_PlotPropertyName[192:219],
	_PlotPropertyName[219:247],
	_PlotPropertyName[247:274],
	_PlotPropertyName[274:302],
	_PlotPropertyName[302:318],
	_PlotPropertyName[318:336],
	_PlotPropertyName[336:354],
	_PlotPropertyName[354:371],
}

// PlotPropertyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PlotPropertyString(s string) (PlotProperty, error) {
	if val, ok := _PlotPropertyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PlotPropertyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PlotProperty values", s)
}

// PlotPropertyValues returns all values of the enum
func PlotPropertyValues() []PlotProperty {
	return _PlotPropertyValues
}

// PlotPropertyStrings returns a slice of all String values of the enum
func PlotPropertyStrings() []string {
	strs := make([]string, len(_PlotPropertyNames))
	copy(strs, _PlotPropertyNames)
	return strs
}

// IsAPlotProperty returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PlotProperty) IsAPlotProperty() bool {
	for _, v := range _PlotPropertyValues {
		if i == v {
			return true
		}
	}
	return false
}
