// Code generated by "stringer -type=StyleColorID,StyleVarID -output=StyleIDs_string.go -linecomment"; DO NOT EDIT.

package giu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StyleColorText-0]
	_ = x[StyleColorTextDisabled-1]
	_ = x[StyleColorWindowBg-2]
	_ = x[StyleColorChildBg-3]
	_ = x[StyleColorPopupBg-4]
	_ = x[StyleColorBorder-5]
	_ = x[StyleColorBorderShadow-6]
	_ = x[StyleColorFrameBg-7]
	_ = x[StyleColorFrameBgHovered-8]
	_ = x[StyleColorFrameBgActive-9]
	_ = x[StyleColorTitleBg-10]
	_ = x[StyleColorTitleBgActive-11]
	_ = x[StyleColorTitleBgCollapsed-12]
	_ = x[StyleColorMenuBarBg-13]
	_ = x[StyleColorScrollbarBg-14]
	_ = x[StyleColorScrollbarGrab-15]
	_ = x[StyleColorScrollbarGrabHovered-16]
	_ = x[StyleColorScrollbarGrabActive-17]
	_ = x[StyleColorCheckMark-18]
	_ = x[StyleColorSliderGrab-19]
	_ = x[StyleColorSliderGrabActive-20]
	_ = x[StyleColorButton-21]
	_ = x[StyleColorButtonHovered-22]
	_ = x[StyleColorButtonActive-23]
	_ = x[StyleColorHeader-24]
	_ = x[StyleColorHeaderHovered-25]
	_ = x[StyleColorHeaderActive-26]
	_ = x[StyleColorSeparator-27]
	_ = x[StyleColorSeparatorHovered-28]
	_ = x[StyleColorSeparatorActive-29]
	_ = x[StyleColorResizeGrip-30]
	_ = x[StyleColorResizeGripHovered-31]
	_ = x[StyleColorResizeGripActive-32]
	_ = x[StyleColorTab-33]
	_ = x[StyleColorTabHovered-34]
	_ = x[StyleColorTabActive-35]
	_ = x[StyleColorTabUnfocused-36]
	_ = x[StyleColorTabUnfocusedActive-37]
	_ = x[StyleColorPlotLines-40]
	_ = x[StyleColorPlotLinesHovered-41]
	_ = x[StyleColorPlotHistogram-42]
	_ = x[StyleColorPlotHistogramHovered-43]
	_ = x[StyleColorTableHeaderBg-44]
	_ = x[StyleColorTableBorderStrong-45]
	_ = x[StyleColorTableBorderLight-46]
	_ = x[StyleColorTableRowBg-47]
	_ = x[StyleColorTableRowBgAlt-48]
	_ = x[StyleColorTextSelectedBg-49]
	_ = x[StyleColorDragDropTarget-50]
	_ = x[StyleColorNavHighlight-51]
	_ = x[StyleColorNavWindowingHighlight-52]
	_ = x[StyleColorNavWindowingDimBg-53]
	_ = x[StyleColorModalWindowDimBg-54]
}

const (
	_StyleColorID_name_0 = "colordisabled-colorbackground-colorchild-background-colorpopup-background-colorborder-colorborder-shadow-colorframe-background-colorframe-background-hovered-colorframe-background-active-colortitle-background-colortitle-background-active-colortitle-background-collapsed-colormenu-bar-background-colorscrollbar-background-colorscrollbar-grab-colorscrollbar-grab-hovered-colorscrollbar-grab-active-colorcheckmark-colorslider-grab-colorslider-grab-active-colorbutton-colorbutton-hovered-colorbutton-active-colorheader-colorheader-hovered-colorheader-active-colorseparator-colorseparator-hovered-colorseparator-active-colorresize-grip-colorresize-grip-hovered-colorresize-grip-active-colortab-colortab-hovered-colortab-active-colortab-unfocused-colortab-unfocused-active-color"
	_StyleColorID_name_1 = "plot-lines-colorplot-lines-hovered-colorplot-histogram-colorplot-histogram-hovered-colortable-header-background-colortable-border-strong-colortable-border-light-colortable-row-background-colortable-row-alternate-background-colortext-selected-background-colordrag-drop-target-colornavigation-highlight-colorwindowing-highlight-colorwindowing-dim-background-colormodal-window-dim-background-color"
)

var (
	_StyleColorID_index_0 = [...]uint16{0, 5, 19, 35, 57, 79, 91, 110, 132, 162, 191, 213, 242, 274, 299, 325, 345, 373, 400, 415, 432, 456, 468, 488, 507, 519, 539, 558, 573, 596, 618, 635, 660, 684, 693, 710, 726, 745, 771}
	_StyleColorID_index_1 = [...]uint16{0, 16, 40, 60, 88, 117, 142, 166, 192, 228, 258, 280, 306, 331, 361, 394}
)

func (i StyleColorID) String() string {
	switch {
	case 0 <= i && i <= 37:
		return _StyleColorID_name_0[_StyleColorID_index_0[i]:_StyleColorID_index_0[i+1]]
	case 40 <= i && i <= 54:
		i -= 40
		return _StyleColorID_name_1[_StyleColorID_index_1[i]:_StyleColorID_index_1[i+1]]
	default:
		return "StyleColorID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StyleVarAlpha-0]
	_ = x[StyleVarDisabledAlpha-1]
	_ = x[StyleVarWindowPadding-2]
	_ = x[StyleVarWindowRounding-3]
	_ = x[StyleVarWindowBorderSize-4]
	_ = x[StyleVarWindowMinSize-5]
	_ = x[StyleVarWindowTitleAlign-6]
	_ = x[StyleVarChildRounding-7]
	_ = x[StyleVarChildBorderSize-8]
	_ = x[StyleVarPopupRounding-9]
	_ = x[StyleVarPopupBorderSize-10]
	_ = x[StyleVarFramePadding-11]
	_ = x[StyleVarFrameRounding-12]
	_ = x[StyleVarFrameBorderSize-13]
	_ = x[StyleVarItemSpacing-14]
	_ = x[StyleVarItemInnerSpacing-15]
	_ = x[StyleVarIndentSpacing-16]
	_ = x[StyleVarCellPadding-17]
	_ = x[StyleVarScrollbarSize-18]
	_ = x[StyleVarScrollbarRounding-19]
	_ = x[StyleVarGrabMinSize-20]
	_ = x[StyleVarGrabRounding-21]
	_ = x[StyleVarTabRounding-22]
	_ = x[StyleVarTabBarBorderSize-23]
	_ = x[StyleVarButtonTextAlign-24]
	_ = x[StyleVarSelectableTextAlign-25]
	_ = x[StyleVarSeparatorTextBorderSize-26]
	_ = x[StyleVarSeparatorTextAlign-27]
	_ = x[StyleVarSeparatorTextPadding-28]
	_ = x[StyleVarDockingSeparatorSize-29]
}

const _StyleVarID_name = "alphadisabled-alphawindow-paddingwindow-roundingwindow-border-sizewindow-minValue-sizewindow-title-alignchild-roundingchild-border-sizepopup-roundingpopup-border-sizeframe-paddingframe-roundingframe-border-sizeitem-spacingitem-inner-spacingindent-spacingStyleVarCellPaddingscrollbar-sizescrollbar-roundinggrab-minValue-sizegrab-roundingtab-roundingStyleVarTabBarBorderSizebutton-text-alignselectable-text-alignStyleVarSeparatorTextBorderSizeStyleVarSeparatorTextAlignStyleVarSeparatorTextPaddingStyleVarDockingSeparatorSize"

var _StyleVarID_index = [...]uint16{0, 5, 19, 33, 48, 66, 81, 99, 113, 130, 144, 161, 174, 188, 205, 217, 235, 249, 268, 282, 300, 313, 326, 338, 362, 379, 400, 431, 457, 485, 513}

func (i StyleVarID) String() string {
	if i < 0 || i >= StyleVarID(len(_StyleVarID_index)-1) {
		return "StyleVarID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StyleVarID_name[_StyleVarID_index[i]:_StyleVarID_index[i+1]]
}
