package giu

import (
	"github.com/AllenDang/cimgui-go"
)

// Here are the style IDs for styling imgui apps.
// For details about each of attributes read comment above them.

// go-generate String() andStringToEnum methods
//go:generate stringer -type=StyleColorID,StyleVarID -output=StyleIDs_string.go -linecomment
// NOTE: string2enum is https://github.com/mewspring/tools
//go:generate string2enum -samepkg -type=StyleColorID,StyleVarID -output=StyleIDs_string2enum.go -linecomment

// StyleColorID identifies a color in the UI style.
type StyleColorID cimgui.ImGuiCol

// StyleColor identifier.
// NOTE: comments are used for CSS conversion and are generated by stringer and string2enum.
const (
	StyleColorText                  = StyleColorID(cimgui.ImGuiCol_Text)                  // color
	StyleColorTextDisabled          = StyleColorID(cimgui.ImGuiCol_TextDisabled)          // disabled-color
	StyleColorWindowBg              = StyleColorID(cimgui.ImGuiCol_WindowBg)              // background-color
	StyleColorChildBg               = StyleColorID(cimgui.ImGuiCol_ChildBg)               // child-background-color
	StyleColorPopupBg               = StyleColorID(cimgui.ImGuiCol_PopupBg)               // popup-background-color
	StyleColorBorder                = StyleColorID(cimgui.ImGuiCol_Border)                // border-color
	StyleColorBorderShadow          = StyleColorID(cimgui.ImGuiCol_BorderShadow)          // border-shadow-color
	StyleColorFrameBg               = StyleColorID(cimgui.ImGuiCol_FrameBg)               // frame-background-color
	StyleColorFrameBgHovered        = StyleColorID(cimgui.ImGuiCol_FrameBgHovered)        // frame-background-hovered-color
	StyleColorFrameBgActive         = StyleColorID(cimgui.ImGuiCol_FrameBgActive)         // frame-background-active-color
	StyleColorTitleBg               = StyleColorID(cimgui.ImGuiCol_TitleBg)               // title-background-color
	StyleColorTitleBgActive         = StyleColorID(cimgui.ImGuiCol_TitleBgActive)         // title-background-active-color
	StyleColorTitleBgCollapsed      = StyleColorID(cimgui.ImGuiCol_TitleBgCollapsed)      // title-background-collapsed-color
	StyleColorMenuBarBg             = StyleColorID(cimgui.ImGuiCol_MenuBarBg)             // menu-bar-background-color
	StyleColorScrollbarBg           = StyleColorID(cimgui.ImGuiCol_ScrollbarBg)           // scrollbar-background-color
	StyleColorScrollbarGrab         = StyleColorID(cimgui.ImGuiCol_ScrollbarGrab)         // scrollbar-grab-color
	StyleColorScrollbarGrabHovered  = StyleColorID(cimgui.ImGuiCol_ScrollbarGrabHovered)  // scrollbar-grab-hovered-color
	StyleColorScrollbarGrabActive   = StyleColorID(cimgui.ImGuiCol_ScrollbarGrabActive)   // scrollbar-grab-active-color
	StyleColorCheckMark             = StyleColorID(cimgui.ImGuiCol_CheckMark)             // checkmark-color
	StyleColorSliderGrab            = StyleColorID(cimgui.ImGuiCol_SliderGrab)            // slider-grab-color
	StyleColorSliderGrabActive      = StyleColorID(cimgui.ImGuiCol_SliderGrabActive)      // slider-grab-active-color
	StyleColorButton                = StyleColorID(cimgui.ImGuiCol_Button)                // button-color
	StyleColorButtonHovered         = StyleColorID(cimgui.ImGuiCol_ButtonHovered)         // button-hovered-color
	StyleColorButtonActive          = StyleColorID(cimgui.ImGuiCol_ButtonActive)          // button-active-color
	StyleColorHeader                = StyleColorID(cimgui.ImGuiCol_Header)                // header-color
	StyleColorHeaderHovered         = StyleColorID(cimgui.ImGuiCol_HeaderHovered)         // header-hovered-color
	StyleColorHeaderActive          = StyleColorID(cimgui.ImGuiCol_HeaderActive)          // header-active-color
	StyleColorSeparator             = StyleColorID(cimgui.ImGuiCol_Separator)             // separator-color
	StyleColorSeparatorHovered      = StyleColorID(cimgui.ImGuiCol_SeparatorHovered)      // separator-hovered-color
	StyleColorSeparatorActive       = StyleColorID(cimgui.ImGuiCol_SeparatorActive)       // separator-active-color
	StyleColorResizeGrip            = StyleColorID(cimgui.ImGuiCol_ResizeGrip)            // resize-grip-color
	StyleColorResizeGripHovered     = StyleColorID(cimgui.ImGuiCol_ResizeGripHovered)     // resize-grip-hovered-color
	StyleColorResizeGripActive      = StyleColorID(cimgui.ImGuiCol_ResizeGripActive)      // resize-grip-active-color
	StyleColorTab                   = StyleColorID(cimgui.ImGuiCol_Tab)                   // tab-color
	StyleColorTabHovered            = StyleColorID(cimgui.ImGuiCol_TabHovered)            // tab-hovered-color
	StyleColorTabActive             = StyleColorID(cimgui.ImGuiCol_TabActive)             // tab-active-color
	StyleColorTabUnfocused          = StyleColorID(cimgui.ImGuiCol_TabUnfocused)          // tab-unfocused-color
	StyleColorTabUnfocusedActive    = StyleColorID(cimgui.ImGuiCol_TabUnfocusedActive)    // tab-unfocused-active-color
	StyleColorPlotLines             = StyleColorID(cimgui.ImGuiCol_PlotLines)             // plot-lines-color
	StyleColorPlotLinesHovered      = StyleColorID(cimgui.ImGuiCol_PlotLinesHovered)      // plot-lines-hovered-color
	StyleColorProgressBarActive     = StyleColorPlotLinesHovered                          // progress-bar-active-color
	StyleColorPlotHistogram         = StyleColorID(cimgui.ImGuiCol_PlotHistogram)         // plot-histogram-color
	StyleColorPlotHistogramHovered  = StyleColorID(cimgui.ImGuiCol_PlotHistogramHovered)  // plot-histogram-hovered-color
	StyleColorTableHeaderBg         = StyleColorID(cimgui.ImGuiCol_TableHeaderBg)         // table-header-background-color
	StyleColorTableBorderStrong     = StyleColorID(cimgui.ImGuiCol_TableBorderStrong)     // table-border-strong-color
	StyleColorTableBorderLight      = StyleColorID(cimgui.ImGuiCol_TableBorderLight)      // table-border-light-color
	StyleColorTableRowBg            = StyleColorID(cimgui.ImGuiCol_TableRowBg)            // table-row-background-color
	StyleColorTableRowBgAlt         = StyleColorID(cimgui.ImGuiCol_TableRowBgAlt)         // table-row-alternate-background-color
	StyleColorTextSelectedBg        = StyleColorID(cimgui.ImGuiCol_TextSelectedBg)        // text-selected-background-color
	StyleColorDragDropTarget        = StyleColorID(cimgui.ImGuiCol_DragDropTarget)        // drag-drop-target-color
	StyleColorNavHighlight          = StyleColorID(cimgui.ImGuiCol_NavHighlight)          // navigation-highlight-color
	StyleColorNavWindowingHighlight = StyleColorID(cimgui.ImGuiCol_NavWindowingHighlight) // windowing-highlight-color
	StyleColorNavWindowingDimBg     = StyleColorID(cimgui.ImGuiCol_NavWindowingDimBg)     // windowing-dim-background-color
	StyleColorModalWindowDimBg      = StyleColorID(cimgui.ImGuiCol_ModalWindowDimBg)      // modal-window-dim-background-color
)

// StyleVarID identifies a style variable in the UI style.
type StyleVarID cimgui.ImGuiStyleVar

// Style IDs.
// comments at same line is a CSS name.
const (
	// StyleVarAlpha is a float.
	StyleVarAlpha = StyleVarID(cimgui.ImGuiStyleVar_Alpha) // alpha
	// StyleVarDisabledAlpha is a float.
	StyleVarDisabledAlpha = StyleVarID(cimgui.ImGuiStyleVar_DisabledAlpha) // disabled-alpha
	// StyleVarWindowPadding is a Vec2.
	StyleVarWindowPadding = StyleVarID(cimgui.ImGuiStyleVar_WindowPadding) // window-padding
	// StyleVarWindowRounding is a float.
	StyleVarWindowRounding = StyleVarID(cimgui.ImGuiStyleVar_WindowRounding) // window-rounding
	// StyleVarWindowBorderSize is a float.
	StyleVarWindowBorderSize = StyleVarID(cimgui.ImGuiStyleVar_WindowBorderSize) // window-border-size
	// StyleVarWindowMinSize is a Vec2.
	StyleVarWindowMinSize = StyleVarID(cimgui.ImGuiStyleVar_WindowMinSize) // window-min-size
	// StyleVarWindowTitleAlign is a Vec2.
	StyleVarWindowTitleAlign = StyleVarID(cimgui.ImGuiStyleVar_WindowTitleAlign) // window-title-align
	// StyleVarChildRounding is a float.
	StyleVarChildRounding = StyleVarID(cimgui.ImGuiStyleVar_ChildRounding) // child-rounding
	// StyleVarChildBorderSize is a float.
	StyleVarChildBorderSize = StyleVarID(cimgui.ImGuiStyleVar_ChildBorderSize) // child-border-size
	// StyleVarPopupRounding is a float.
	StyleVarPopupRounding = StyleVarID(cimgui.ImGuiStyleVar_PopupRounding) // popup-rounding
	// StyleVarPopupBorderSize is a float.
	StyleVarPopupBorderSize = StyleVarID(cimgui.ImGuiStyleVar_PopupBorderSize) // popup-border-size
	// StyleVarFramePadding is a Vec2.
	StyleVarFramePadding = StyleVarID(cimgui.ImGuiStyleVar_FramePadding) // frame-padding
	// StyleVarFrameRounding is a float.
	StyleVarFrameRounding = StyleVarID(cimgui.ImGuiStyleVar_FrameRounding) // frame-rounding
	// StyleVarFrameBorderSize is a float.
	StyleVarFrameBorderSize = StyleVarID(cimgui.ImGuiStyleVar_FrameBorderSize) // frame-border-size
	// StyleVarItemSpacing is a Vec2.
	StyleVarItemSpacing = StyleVarID(cimgui.ImGuiStyleVar_ItemSpacing) // item-spacing
	// StyleVarItemInnerSpacing is a Vec2.
	StyleVarItemInnerSpacing = StyleVarID(cimgui.ImGuiStyleVar_ItemInnerSpacing) // item-inner-spacing
	// StyleVarIndentSpacing is a float.
	StyleVarIndentSpacing = StyleVarID(cimgui.ImGuiStyleVar_IndentSpacing) // indent-spacing
	// StyleVarScrollbarSize is a float.
	StyleVarScrollbarSize = StyleVarID(cimgui.ImGuiStyleVar_ScrollbarSize) // scrollbar-size
	// StyleVarScrollbarRounding is a float.
	StyleVarScrollbarRounding = StyleVarID(cimgui.ImGuiStyleVar_ScrollbarRounding) // scrollbar-rounding
	// StyleVarGrabMinSize is a float.
	StyleVarGrabMinSize = StyleVarID(cimgui.ImGuiStyleVar_GrabMinSize) // grab-min-size
	// StyleVarGrabRounding is a float.
	StyleVarGrabRounding = StyleVarID(cimgui.ImGuiStyleVar_GrabRounding) // grab-rounding
	// StyleVarTabRounding is a float.
	StyleVarTabRounding = StyleVarID(cimgui.ImGuiStyleVar_TabRounding) // tab-rounding
	// StyleVarButtonTextAlign is a Vec2.
	StyleVarButtonTextAlign = StyleVarID(cimgui.ImGuiStyleVar_ButtonTextAlign) // button-text-align
	// StyleVarSelectableTextAlign is a Vec2.
	StyleVarSelectableTextAlign = StyleVarID(cimgui.ImGuiStyleVar_SelectableTextAlign) // selectable-text-align
)

// IsVec2 returns true if the style var id should be processed as imgui.Vec2
// if not, it is interpreted as float32.
func (i StyleVarID) IsVec2() bool {
	lookup := map[StyleVarID]bool{
		// StyleVarWindowPadding is a Vec2.
		StyleVarWindowPadding:    true,
		StyleVarWindowMinSize:    true,
		StyleVarWindowTitleAlign: true,
		StyleVarFramePadding:     true,
		StyleVarItemSpacing:      true,
		// StyleVarItemInnerSpacing is a Vec2.
		StyleVarItemInnerSpacing:    true,
		StyleVarButtonTextAlign:     true,
		StyleVarSelectableTextAlign: true,
	}

	result, ok := lookup[i]

	return result && ok
}
