// Code generated by "enumer -linecomment -type=StylePlotVarID ."; DO NOT EDIT.

package giu

import (
	"fmt"
	"strings"
)

const (
	_StylePlotVarIDName_0      = "plot-default-sizeplot-min-sizeplot-border-sizeplot-minor-alphaplot-major-tick-lenplot-minor-tick-lenplot-major-tick-sizeplot-minor-tick-sizeplot-major-grid-sizeplot-minor-grid-sizeplot-paddingplot-label-paddingplot-legend-paddingplot-legend-inner-paddingplot-legend-spacingplot-mouse-pos-paddingplot-annotation-paddingplot-fit-padding"
	_StylePlotVarIDLowerName_0 = "plot-default-sizeplot-min-sizeplot-border-sizeplot-minor-alphaplot-major-tick-lenplot-minor-tick-lenplot-major-tick-sizeplot-minor-tick-sizeplot-major-grid-sizeplot-minor-grid-sizeplot-paddingplot-label-paddingplot-legend-paddingplot-legend-inner-paddingplot-legend-spacingplot-mouse-pos-paddingplot-annotation-paddingplot-fit-padding"
	_StylePlotVarIDName_1      = "StylePlotVarCOUNT"
	_StylePlotVarIDLowerName_1 = "styleplotvarcount"
)

var (
	_StylePlotVarIDIndex_0 = [...]uint16{0, 17, 30, 46, 62, 81, 100, 120, 140, 160, 180, 192, 210, 229, 254, 273, 295, 318, 334}
	_StylePlotVarIDIndex_1 = [...]uint8{0, 17}
)

func (i StylePlotVarID) String() string {
	switch {
	case 0 <= i && i <= 17:
		return _StylePlotVarIDName_0[_StylePlotVarIDIndex_0[i]:_StylePlotVarIDIndex_0[i+1]]
	case i == 20:
		return _StylePlotVarIDName_1
	default:
		return fmt.Sprintf("StylePlotVarID(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StylePlotVarIDNoOp() {
	var x [1]struct{}
	_ = x[StylePlotVarPlotDefaultSize-(0)]
	_ = x[StylePlotVarPlotMinSize-(1)]
	_ = x[StylePlotVarPlotBorderSize-(2)]
	_ = x[StylePlotVarMinorAlpha-(3)]
	_ = x[StylePlotVarMajorTickLen-(4)]
	_ = x[StylePlotVarMinorTickLen-(5)]
	_ = x[StylePlotVarMajorTickSize-(6)]
	_ = x[StylePlotVarMinorTickSize-(7)]
	_ = x[StylePlotVarMajorGridSize-(8)]
	_ = x[StylePlotVarMinorGridSize-(9)]
	_ = x[StylePlotVarPlotPadding-(10)]
	_ = x[StylePlotVarLabelPadding-(11)]
	_ = x[StylePlotVarLegendPadding-(12)]
	_ = x[StylePlotVarLegendInnerPadding-(13)]
	_ = x[StylePlotVarLegendSpacing-(14)]
	_ = x[StylePlotVarMousePosPadding-(15)]
	_ = x[StylePlotVarAnnotationPadding-(16)]
	_ = x[StylePlotVarFitPadding-(17)]
	_ = x[StylePlotVarCOUNT-(20)]
}

var _StylePlotVarIDValues = []StylePlotVarID{StylePlotVarPlotDefaultSize, StylePlotVarPlotMinSize, StylePlotVarPlotBorderSize, StylePlotVarMinorAlpha, StylePlotVarMajorTickLen, StylePlotVarMinorTickLen, StylePlotVarMajorTickSize, StylePlotVarMinorTickSize, StylePlotVarMajorGridSize, StylePlotVarMinorGridSize, StylePlotVarPlotPadding, StylePlotVarLabelPadding, StylePlotVarLegendPadding, StylePlotVarLegendInnerPadding, StylePlotVarLegendSpacing, StylePlotVarMousePosPadding, StylePlotVarAnnotationPadding, StylePlotVarFitPadding, StylePlotVarCOUNT}

var _StylePlotVarIDNameToValueMap = map[string]StylePlotVarID{
	_StylePlotVarIDName_0[0:17]:         StylePlotVarPlotDefaultSize,
	_StylePlotVarIDLowerName_0[0:17]:    StylePlotVarPlotDefaultSize,
	_StylePlotVarIDName_0[17:30]:        StylePlotVarPlotMinSize,
	_StylePlotVarIDLowerName_0[17:30]:   StylePlotVarPlotMinSize,
	_StylePlotVarIDName_0[30:46]:        StylePlotVarPlotBorderSize,
	_StylePlotVarIDLowerName_0[30:46]:   StylePlotVarPlotBorderSize,
	_StylePlotVarIDName_0[46:62]:        StylePlotVarMinorAlpha,
	_StylePlotVarIDLowerName_0[46:62]:   StylePlotVarMinorAlpha,
	_StylePlotVarIDName_0[62:81]:        StylePlotVarMajorTickLen,
	_StylePlotVarIDLowerName_0[62:81]:   StylePlotVarMajorTickLen,
	_StylePlotVarIDName_0[81:100]:       StylePlotVarMinorTickLen,
	_StylePlotVarIDLowerName_0[81:100]:  StylePlotVarMinorTickLen,
	_StylePlotVarIDName_0[100:120]:      StylePlotVarMajorTickSize,
	_StylePlotVarIDLowerName_0[100:120]: StylePlotVarMajorTickSize,
	_StylePlotVarIDName_0[120:140]:      StylePlotVarMinorTickSize,
	_StylePlotVarIDLowerName_0[120:140]: StylePlotVarMinorTickSize,
	_StylePlotVarIDName_0[140:160]:      StylePlotVarMajorGridSize,
	_StylePlotVarIDLowerName_0[140:160]: StylePlotVarMajorGridSize,
	_StylePlotVarIDName_0[160:180]:      StylePlotVarMinorGridSize,
	_StylePlotVarIDLowerName_0[160:180]: StylePlotVarMinorGridSize,
	_StylePlotVarIDName_0[180:192]:      StylePlotVarPlotPadding,
	_StylePlotVarIDLowerName_0[180:192]: StylePlotVarPlotPadding,
	_StylePlotVarIDName_0[192:210]:      StylePlotVarLabelPadding,
	_StylePlotVarIDLowerName_0[192:210]: StylePlotVarLabelPadding,
	_StylePlotVarIDName_0[210:229]:      StylePlotVarLegendPadding,
	_StylePlotVarIDLowerName_0[210:229]: StylePlotVarLegendPadding,
	_StylePlotVarIDName_0[229:254]:      StylePlotVarLegendInnerPadding,
	_StylePlotVarIDLowerName_0[229:254]: StylePlotVarLegendInnerPadding,
	_StylePlotVarIDName_0[254:273]:      StylePlotVarLegendSpacing,
	_StylePlotVarIDLowerName_0[254:273]: StylePlotVarLegendSpacing,
	_StylePlotVarIDName_0[273:295]:      StylePlotVarMousePosPadding,
	_StylePlotVarIDLowerName_0[273:295]: StylePlotVarMousePosPadding,
	_StylePlotVarIDName_0[295:318]:      StylePlotVarAnnotationPadding,
	_StylePlotVarIDLowerName_0[295:318]: StylePlotVarAnnotationPadding,
	_StylePlotVarIDName_0[318:334]:      StylePlotVarFitPadding,
	_StylePlotVarIDLowerName_0[318:334]: StylePlotVarFitPadding,
	_StylePlotVarIDName_1[0:17]:         StylePlotVarCOUNT,
	_StylePlotVarIDLowerName_1[0:17]:    StylePlotVarCOUNT,
}

var _StylePlotVarIDNames = []string{
	_StylePlotVarIDName_0[0:17],
	_StylePlotVarIDName_0[17:30],
	_StylePlotVarIDName_0[30:46],
	_StylePlotVarIDName_0[46:62],
	_StylePlotVarIDName_0[62:81],
	_StylePlotVarIDName_0[81:100],
	_StylePlotVarIDName_0[100:120],
	_StylePlotVarIDName_0[120:140],
	_StylePlotVarIDName_0[140:160],
	_StylePlotVarIDName_0[160:180],
	_StylePlotVarIDName_0[180:192],
	_StylePlotVarIDName_0[192:210],
	_StylePlotVarIDName_0[210:229],
	_StylePlotVarIDName_0[229:254],
	_StylePlotVarIDName_0[254:273],
	_StylePlotVarIDName_0[273:295],
	_StylePlotVarIDName_0[295:318],
	_StylePlotVarIDName_0[318:334],
	_StylePlotVarIDName_1[0:17],
}

// StylePlotVarIDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StylePlotVarIDString(s string) (StylePlotVarID, error) {
	if val, ok := _StylePlotVarIDNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StylePlotVarIDNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to StylePlotVarID values", s)
}

// StylePlotVarIDValues returns all values of the enum
func StylePlotVarIDValues() []StylePlotVarID {
	return _StylePlotVarIDValues
}

// StylePlotVarIDStrings returns a slice of all String values of the enum
func StylePlotVarIDStrings() []string {
	strs := make([]string, len(_StylePlotVarIDNames))
	copy(strs, _StylePlotVarIDNames)
	return strs
}

// IsAStylePlotVarID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i StylePlotVarID) IsAStylePlotVarID() bool {
	for _, v := range _StylePlotVarIDValues {
		if i == v {
			return true
		}
	}
	return false
}
