// Code generated by "stringer -type=SurfaceState"; DO NOT EDIT.

package giu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SsNone-0]
	_ = x[SsLoading-1]
	_ = x[SsFailure-2]
	_ = x[SsSuccess-3]
}

const _SurfaceState_name = "SsNoneSsLoadingSsFailureSsSuccess"

var _SurfaceState_index = [...]uint8{0, 6, 15, 24, 33}

func (i SurfaceState) String() string {
	if i < 0 || i >= SurfaceState(len(_SurfaceState_index)-1) {
		return "SurfaceState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SurfaceState_name[_SurfaceState_index[i]:_SurfaceState_index[i+1]]
}
