name: Bug report
description: Create a report to help us improve
title: '[bug]'
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happend
    attributes:
      label: What happend?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: code-example
    attributes:
      label: Code example
      description: |
        A minimalistic code example which allows to reproduce the behavior.
        In worst case, link to public repo when the behavior could be noticed.
      placeholder: code / URL
      value: |
        <details><summary><code>main.go</code></summary>

        ```golang
        // put your code here!
        ```

        </details>
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: What should we do to reproduce the behavior?
      placeholder: |
        1. Run my demo
        2. will see the crash...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of giu are you running?
      placeholder: e.g. v0.14.1, e79933c8e3e77e6e2ae417130d8f46fb4bd6a946
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        To extract giu version information, run `git rev-parse HEAD` in giu directory,
        or find line starting with `github.com/AllenDang/giu` in your `go.mod` file.
  - type: input
    id: os
    attributes:
      label: OS
      description: What operating system are you useing?
      placeholder: windows 10, Ubuntu...
    validations:
      required: true
