name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  Building:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/virtual-environments#available-environments
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - if: startsWith(matrix.os,'ubuntu')
        name: Set up LibGL, Mesa & X11 libraries
        run: |
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get install -y libgtk-3-dev libasound2-dev libxxf86vm-dev
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
        id: go

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: run go get
        run: go get -v -t -d ./...
      - name: build
        run: |
            go build examples/widgets/widgets.go

      - name: test
        run: |
          go test ./...
