name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up LibGL, Mesa & X11 libraries
        run: |
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get install -y libgtk-3-dev libasound2-dev libxxf86vm-dev
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
